In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


NumPy Creating Arrays

In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

In [3]:
import numpy as np

arr=np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


0-D Arrays

0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [4]:
import numpy as np

arr=np.array(45)

print(arr)

45


1-D Arrays.

In [5]:
import numpy as np

arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


2-D Arrays

In [7]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])

print(arr)

[[1 2 3]
 [4 5 6]]


3-D Arrays

In [11]:
import numpy as np

arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Check Number of Dimensions

In [13]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [17]:
import numpy as np
arr=np.array([1,2,3,4,5], ndmin=5)
print(arr)
print("Number of dimensions: ",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimensions:  5


NumPy Array Indexing

In [18]:
arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


Accessing Array elements

In [19]:
print(arr[0])

1


In [20]:
arr[1]

2

In [21]:
print(arr[3]+arr[4])

9


Access 2-D Arrays

In [22]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [23]:
print('5th element on 2nd row: ', arr[1,4])

5th element on 2nd row:  10


Access 3-D Arrays

In [24]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1,0,2])

9


Negative Indexing

Use negative indexing to access an array from the end.

In [25]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1,-1])

Last element from 2nd dim:  10


NumPy Array Slicing

Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [26]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[1:5]

array([2, 3, 4, 5])

In [27]:
arr[:4]

array([1, 2, 3, 4])

In [28]:
arr[4:]

array([5, 6, 7, 8, 9])

Negative Slicing

Use the minus operator to refer to an index from the end:

In [30]:
arr[-3:-1]
#arr[-1:-3]

array([7, 8])

Step

In [31]:
arr[1:8:2]

array([2, 4, 6, 8])

In [32]:
arr[::2]

array([1, 3, 5, 7, 9])

Slicing 2-D Arrays

In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


From both elements, return index 2

In [34]:
print(arr[0:2, 2])

[3 8]


From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

In [35]:
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


NumPy Data Types

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )